apiVersion: v1
kind: Namespace
metadata:
  name: spark-operator
  labels:
    name: spark-operator
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-alpha
  labels:
    name: team-alpha
---
apiVersion: v1
kind: Namespace
metadata:
  name: team-beta
  labels:
    name: team-beta
