
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airflow
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://airflow-helm.github.io/charts
    chart: airflow
    targetRevision: 1.15.0  # Replace with the Airflow Helm chart version you want
    helm:
      valueFiles:
        - values.yaml  # Path to custom values.yaml in your Git repository
  destination:
    server: https://kubernetes.default.svc
    namespace: airflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
